### PR TITLE
Render dynamic holder fields

### PR DESCRIPTION
**Pull request by tf-rene**

### CODE REVIEW

**Comment by ft-worker** [comment]
@tf-rene should I review and/or merge this PR? I think it's incomplete. Am I right?

**Comment by tf-rene** [comment]
@ft-worker Please review, it's still missing sending the ticket holders data in the api request

**Comment by ft-worker** [comment]
@tf-rene please add ticket holders data in the api request and make sure validations are working properly. Also, please, back-merge master branch, now this branch has conflicts. After these changes I'll review PR.

**Comment by tf-rene** [comment]
[Make ticket holders section dynamic and add email and phone number](https://trello.com/c/RwTkrHB9/422-make-ticket-holders-section-dynamic-and-add-email-and-phone-number)

**Pull request merged**
